config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do

    resources :gists, only: :index
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
  end

  resource :feedbacks, only: %i[new create],
                       path: "feedback",
                       path_names: { new: '/' }

  get 'badges', to: 'badges#received'
  get 'badges-review', to: 'badges#index'
end

app/models/admin.rb
class Admin < User

  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def max_answers
    errors.add(question, 'Answers limit reached!') if question.answers.count >= 4
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  RULES = %i[test_category attempts tests_level]

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :name, :logo, :rule, :value, presence: true

end

app/models/badges_user.rb
class BadgesUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }
  has_many :tests, dependent: :nullify
  validates :title, presence: true  
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :email, :text

  validates :email, :text, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
  
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true,
                    uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: -1 }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :by_category, (lambda do |name|
    joins(:category)
      .where(categories: {title: name})
      .order(title: :desc)
  end)

  def timer?
    duration > 0
  end

  def self.titles_by_category(name)
    by_category(name).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validatation_set_next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    # set to last because callback later on save!
    self.current_question = test.questions.last if test.timer? && finished?
    
    save!
  end

  def success?
    percent_correct >= 85
  end

  def percent_correct
    correct_questions.to_f / test.questions.count * 100
  end

  def current_question_number
    test_questions.where('id <= ?', current_question.id).count
  end

  def questions_count
    test.questions.count
  end

  def ends_in
    (created_at + test.duration - Time.zone.now).to_i
  end

  private 

  def before_validatation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question.nil?
      test_questions.first
    else
      test_questions.where('id > ?', current_question.id).first
    end
  end

  def test_questions
    test.questions.order(:id)
  end

  def finished?
    ends_in <= 0
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists, dependent: :destroy
  has_many :badges_users, dependent: :destroy
  has_many :badges, through: :badges_users

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: %i[start]
  
  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
    
  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_message(type)
    content_tag :p, flash[type], class: "flash #{type}" if flash[type] 
  end

  def bootsrap_type(type)
    case type
    when "notice" then 'info'
    when "alert" then 'warning'
    when "error" then 'danger'
    end
  end
end

app/helpers/footer_helper.rb
module FooterHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to author, repo, target: '_blank'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    t('.header', test_name: question.test.title)
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-info">
  <span><%= link_to 'TestGuru', root_path, class: 'navbar-brand' %> Admin Panel</span>

  <span><%= link_to 'Gists', admin_gists_path, class: 'navbar-brand' %></span>

  <span><%= link_to 'Badges', admin_badges_path, class: 'navbar-brand' %></span>

  <ul class="nav justify-content-end">
    <li class="nav-item">
      <p>Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru</p>
    </li>
    <li class="nav-item">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  </li>
</nav>

app/views/partials/_feedback_links.html.erb
<li class="nav-item">
  <%= link_to 'Leave feedback', new_feedbacks_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'About', 'about.html', class: 'nav-link' %>
</li>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= bootsrap_type(key) %>" role="alert">
    <%= content_tag :p, message.html_safe %>  
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <small>
      <span>
        <%= current_year %>,
        <%= github_url('Igor Lukashin', 'https://github.com/ilukashin/TN_TestGuru') %>
      </span>
      <span>No tests - no gurus. Find your destiny.</span> 
      <span>
        Learning Project at 
        <%= link_to 'Thinknetica', 'https://thinknetica.com/', target: '_blank' %> 
        Online School.
      </span> 
    </small>
  </div>
</footer>  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <% if user_signed_in? %>
    <p>Welcome, <%= current_user.first_name %> to <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>!</p>

    <% if current_user.admin? %>
      <ul class="nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Admin Panel', admin_tests_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>

    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to 'Badges', badges_path, class: 'nav-link' %>
      </li>
      <%= render 'partials/feedback_links' %>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>

  <% else %>
    <p>Welcome to <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>!</p>
    <ul class="nav justify-content-end">
      <%= render 'partials/feedback_links' %>
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Signup', new_user_registration_path, class: 'nav-link' %>
      </li>
    </ul>
  <% end %>
</nav>