config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do

    resources :gists, only: :index
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
  end

  resource :feedbacks, only: %i[new create],
                       path: "feedback",
                       path_names: { new: '/' }

  get 'badges', to: 'badges#received'
  get 'badges-review', to: 'badges#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def max_answers
    errors.add(question, 'Answers limit reached!') if question.answers.count >= 4
  end

end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@answer.question), notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to @answer.question, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer.question
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li class="list-item">
  <%= answer.body %><br>
  <%= link_to t('.show'), admin_answer_path(answer), class: 'badge badge-info' %>
  <%= link_to t('.edit'), edit_admin_answer_path(answer), class: 'badge badge-warning' %>
  <%= link_to t('.delete'), admin_answer_path(answer),
                        method: :delete,
                        data: { confirm: t('.delete_confirm') },
                        class: 'badge badge-danger' %>

</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>
  <div class="form-group">
    <p>
      <%= form.label :body%> <br>
      <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60, class: 'form-control' %>
    </p>
  </div>

  <div class="form-check">
    <p>
      <%= form.label :correct, class: 'form-check-label' do %>
        <%= form.check_box :correct, id: :answer_correct, class: 'form-check-input' %>
        Correct
      <% end %>
    </p>
  </div>

  <div class="form-group">
    <div class="actions">
      <%= form.submit class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.header') %></h1>

<p><%= @answer.question.body %></p>

<%= render 'form' %>

<%= link_to t('.back'), admin_question_path(@answer.question), class: 'badge badge-secondary' %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>

<p><%= @question.body %></p>

<%= render 'form'%>

<%= link_to t('.back'), admin_question_path(@question), class: 'badge badge-secondary' %>

app/views/admin/answers/show.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b><%= t('.answer') %>:</b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t('.correct') %>:</b>
  <%= @answer.correct %>
</p>

<%= link_to t('.back'), admin_question_path(@answer.question), class: 'badge badge-secondary' %>